set -a
PATH=$PATH:~/bin
SVN_EDITOR=vim
VIRTUAL_ENV_HOME="${HOME}/.virtualenvs"
set +a

parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

set -o vi
export PS1="green-beret \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\]>"
alias gstat='git status ; echo ; git log --pretty=oneline --color=always | head'
alias ls='ls --color'
source ~/.git-completion.bash
complete -C '/usr/local/bin/aws_completer' aws
